# 본 액션의 별칭
name: S3 Upload

# main 브랜치에 push 할 경우 본 액션이 동작함
on:
  push:
    branches: ["main"]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Node.js 환경일 경우에만 해당
      - uses: actions/setup-node@v1
        with:
          node-version: [17.x]
      - name: Setup Yarn
        run: npm install -g yarn
      - name: Start Build
        run: |
          yarn
          yarn build

      # S3 업로드 액션 시작
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}

          # 로컬 프로젝트에서 실제 업로드할 파일의 경로 (디렉토리) '/' 없이 순수 디렉토리명만 기재
          source_dir: ".next"

          # 실제 S3 에 업로드 되는 디렉토리명
          # 업로드가 완료된 후 S3 URL 인 http://portfolio-ureca.s3-website.ap-northeast-2.amazonaws.com/ 뒤에 {destination_dir} 이 그대로 붙음
          destination_dir: "test"
